export const langs = [
  { code: "de", flag: "fi fi-de" },
  { code: "fr", flag: "fi fi-fr" },
  { code: "it", flag: "fi fi-it" },
  { code: "es", flag: "fi fi-es" },
  { code: "sv", flag: "fi fi-se" },
  { code: "bg", flag: "fi fi-bg" },
  { code: "pt", flag: "fi fi-pt" },
  { code: "ru", flag: "fi fi-ru" },
  { code: "tr", flag: "fi fi-tr" },
  { code: "hu", flag: "fi fi-hu" },
  { code: "el", flag: "fi fi-gr" },
  { code: "pl", flag: "fi fi-pl" },
  { code: "nl", flag: "fi fi-nl" },
  { code: "ar", flag: "fi fi-sy" },
  { code: "ja", flag: "fi fi-jp" },
];
