export const HTTP_STATUS = {
    OK: "OK",
    BAD_REQUEST: "BAD_REQUEST",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
}

export const HTTP_STATUS_CODE = {
    OK: 200,
    BAD_REQUEST: 400,
    INTERNAL_SERVER_ERROR: 500
}